version: "2.1"

services:

  event-contribution:
    build:
      context: .
      dockerfile: balena/Dockerfile.app.template
    ports:
      - 9001:9001
    restart: always
    volumes:
      - data:/data

  wifi-connect:
    build:
      context: .
      dockerfile: balena/Dockerfile.wifi.template
    network_mode: host
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
    restart: always
    tmpfs:
      - /tmp/www

volumes:
  data:
