version: "2.1"

services:

  event-contribution:
    build:
      context: .
      dockerfile: balena/Dockerfile.app.template
    ports:
      - 9001:9001
    restart: always
    volumes:
      - data:/data

  wifi-connect:
    build:
      context: balena
      dockerfile: Dockerfile.wifi.template
    network_mode: host
    labels:
      io.balena.features.dbus: 1
    cap_add:
      - NET_ADMIN
    restart: always
    environment:
      PORTAL_SSID: Event Contribution

volumes:
  data: