version: "2.1"

services:

  event-contribution:
    build:
      context: .
      dockerfile: balena/Dockerfile.app.template
    ports:
      - 9001:9001
    restart: always
    volumes:
      - data:/data:rw
      - www:/www:ro

  wifi-connect:
    build:
      context: balena
      dockerfile: Dockerfile.wifi.template
    network_mode: host
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: 1
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: unix:path=/host/run/dbus/system_bus_socket
      UI_DIRECTORY: /www
    restart: always
    volumes:
      - www:/www:ro

volumes:
  data:
  www: