FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine

RUN install_packages mosquitto

COPY mosquitto.conf /etc/mosquitto/mosquitto.conf
COPY dist/ /www/

VOLUME /data

EXPOSE 9001

CMD ["sh", "-c", "chown mosquitto /data && /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf"]