FROM balenalib/%%BALENA_MACHINE_NAME%%-alpine

RUN install_packages mosquitto

COPY mosquitto.conf /etc/mosquitto/mosquitto.conf
COPY *.html /www/
COPY css/ /www/css/
COPY js/ /www/js/

VOLUME /data

EXPOSE 9001

CMD ["sh", "-c", "chown mosquitto /data && /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf"]