FROM balenalib/%%BALENA_MACHINE_NAME%%-debian

RUN install_packages dnsmasq wireless-tools

WORKDIR /app/

RUN curl -s https://api.github.com/repos/balena-io/wifi-connect/releases/latest \
    | grep -ho 'browser_download_url": ".*%%RESIN_ARCH%%\.tar\.gz' \
    | cut -d'"' -f3 \
    | xargs -n1 curl -Ls \
    | tar -xz -C /app/

CMD ["sh", "-c", "/app/wifi-connect && sleep infinity"]
